### ISSUE TITLE
can't download the raw original dataset from baidu 

### ISSUE THREAD

**Issue by khalilsnoussi** [qinnzou/Gait-Recognition-Using-Smartphones#3]
As a user attempting to download the raw dataset, upon visiting the provided link in the readme section (https://pan.baidu.com/s/1VN77r819dhX0bay-0MJucQ) with the code "uhu2," I encounter a message indicating that the dataset has been accessed by 5 people and is restricted to a maximum of 5 users.

**Comment by qinnzou** [comment]
updated link： https://pan.baidu.com/s/1aMiftAukgAuzoZftwJZiDw 
code：140w


-----原始邮件-----
发件人:khalilsnoussi ***@***.***>
发送时间:2024-01-31 07:23:25 (星期三)
收件人: qinnzou/Gait-Recognition-Using-Smartphones ***@***.***>
抄送: Subscribed ***@***.***>
主题: [qinnzou/Gait-Recognition-Using-Smartphones] can't download the raw original dataset from baidu (Issue #3)






As a user attempting to download the raw dataset, upon visiting the provided link in the readme section (https://pan.baidu.com/s/1VN77r819dhX0bay-0MJucQ) with the code "uhu2," I encounter a message indicating that the dataset has been accessed by 5 people and is restricted to a maximum of 5 users.

**Comment by khalilsnoussi** [comment]
thanks alot !
